# Generated by Django 3.2.9 on 2021-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='disablity',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='Parent Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Student Address'),
        ),
    ]
